feat: bump for some dependencies
PUGX/badge-poser pull request #1031
Opened 2023-05-15 14:00 UTC by JellyBellyDev

I apply bump for composer and npm dependencies

2023-05-15 16:09 UTC, garak requested changes

2023-05-15 16:09 UTC, garak commented on composer.json
> +            "php-http/discovery": true
this is not respecting the sorting

2023-05-15 16:12 UTC, JellyBellyDev commented on composer.json
> +            "php-http/discovery": true
Thanks! Fixed!

2023-05-16 06:29 UTC, garak approved these changes

2023-05-16 07:45 UTC, merged