converting cloudformation template to terraform
PUGX/badge-poser pull request #1260
Opened 2024-12-22 12:46 UTC by fabiocicerchia

2024-12-26 21:17 UTC, garak approved these changes

2025-01-03 11:25 UTC, JellyBellyDev requested changes

2025-01-03 11:25 UTC, JellyBellyDev commented on sys/terraform/ecs/task-definition.json
> +      "value": "${env_appenv}"
why not continue with the snake_case?

2025-01-03 11:25 UTC, JellyBellyDev commented on sys/terraform/variables.tf
> +variable "env_appdebug" {
same also here, why not continue with the snake_case?

2025-01-06 09:10 UTC, JellyBellyDev approved these changes
LGTM 👍🏻

2025-01-06 14:24 UTC, merged