WIP: adding github actions
PUGX/badge-poser pull request #542
Opened 2021-05-19 19:10 UTC by AlessandroMinoccheri

2021-05-20 07:48 UTC, JellyBellyDev commented on .github/workflows/build.yml
> +          ${{ runner.os }}-php-
maybe we should add `${{ matrix.php-versions }}` to the key too?

2021-05-20 07:50 UTC, JellyBellyDev commented
I would also add the test of the build of the assets. WDYT?

2021-05-20 07:55 UTC, AlessandroMinoccheri commented
Yes @JellyBellyDev , actually, this is the first tiny step.

2021-05-21 10:06 UTC, JellyBellyDev commented on .github/workflows/build.yml
> +      run: PHP_CS_FIXER_IGNORE_ENV=1 ./bin/php-cs-fixer fix --dry-run -v
`vendor/bin/php-cs-fixer fix --verbose --diff --dry-run` ;)

2021-05-21 10:13 UTC, JellyBellyDev commented on .github/workflows/build.yml
> +
```
    coverage-driver:          
        - "pcov"          
        - "xdebug3"
```

like here: https://github.com/sebastianbergmann/php-code-coverage/blob/master/.github/workflows/ci.yml#L55

2021-05-21 10:13 UTC, JellyBellyDev commented on .github/workflows/build.yml
> +      run: ./bin/phpunit
```
- name: "Run tests with phpunit/phpunit"        
   run: "bin/phpunit -d memory_limit=-1 --coverage-clover clover.xml"
   
- name: "Send code coverage report to Codecov.io"        
   env:          
       CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"        
   run: "bash &lt;(curl -s https://codecov.io/bash) || true"
```

2021-05-24 09:05 UTC, JellyBellyDev commented on tests/Controller/HomeControllerTest.php
> +        var_dump($client->getResponse()->getContent());
clean! ;)

2021-05-25 21:28 UTC, AlessandroMinoccheri commented on .github/workflows/build.yml
> +      run: ./bin/phpunit
It doesn't work :(

2021-05-25 21:28 UTC, AlessandroMinoccheri commented
I am not sure about uploading on codecov @JellyBellyDev

2021-05-26 07:43 UTC, JellyBellyDev requested changes
Please, can you override in the readme the badge for CI powered by github actions?

2021-05-26 07:43 UTC, JellyBellyDev commented on Makefile
> +	.docker_img_deps:
why you add a space?

2021-05-26 07:43 UTC, JellyBellyDev commented on .github/workflows/build.yml
> +        coverage-driver: [ 'pcov', 'xdebug3' ]
we want to leave only pcov?

2021-05-26 07:43 UTC, JellyBellyDev commented on .github/workflows/build.yml
> +    - name: Install dependencies
In the logs of this job i can see: `Warning: Unexpected input(s) 'composer_version', valid inputs are ['version', 'php_version', 'php_extensions', 'command', 'only_args', 'interaction', 'dev', 'progress', 'quiet', 'args', 'ssh_key', 'ssh_key_pub', 'ssh_domain', 'working_dir']`

2021-05-26 07:43 UTC, JellyBellyDev commented on .github/workflows/build.yml
> +        node-version: '14'
we can use `14.14.0` like in `.nvmrc` file?

2021-05-26 16:29 UTC, AlessandroMinoccheri commented
Readme updated @JellyBellyDev and did some fixes.

2021-05-27 12:11 UTC, JellyBellyDev approved these changes
LGTM 👍 

WDYT what do you think if we delete the contents of the dir `.circleci`?

It seems that only this is missing: https://github.com/PUGX/badge-poser/blob/master/.circleci/config.yml#L154

2021-05-27 12:24 UTC, fabiocicerchia approved these changes
👍 LGTM

2021-05-27 15:49 UTC, JellyBellyDev commented
> LGTM 👍
> 
> WDYT what do you think if we delete the contents of the dir `.circleci`?
> 
> It seems that only this is missing: https://github.com/PUGX/badge-poser/blob/master/.circleci/config.yml#L154

i think it is better to remove .circle in a separate pr! ;)

2021-05-27 15:49 UTC, merged