added new workflow for deploying to aws
PUGX/badge-poser pull request #622
Opened 2021-09-23 12:23 UTC by fabiocicerchia

2021-09-24 14:47 UTC, AlessandroMinoccheri commented
Is it already a draft or we can review this PR @fabiocicerchia ?

2021-09-24 17:29 UTC, fabiocicerchia commented
@AlessandroMinoccheri I've tested it locally with [act](https://github.com/nektos/act) and it is now ready ;)

2021-09-24 22:00 UTC, AlessandroMinoccheri approved these changes
LGTM 👍

2021-09-27 07:49 UTC, JellyBellyDev approved these changes
LGTM

2021-09-27 15:55 UTC, drAlberT requested changes

2021-09-27 15:55 UTC, drAlberT commented on .github/workflows/deploy.yml
> +      run: apt-get update && apt-get install -y awscli
the distribution package is usually outdated, consider installing it as recommended in their doc :)

2021-09-27 15:55 UTC, drAlberT commented on Makefile
>  		--template-body=file://$$PWD/sys/cloudformation/stack.yaml \
IIRC it should work wit relative path too

2021-09-27 15:55 UTC, drAlberT commented on Makefile
>  	aws ecr get-login-password --profile $(AWS_PROFILE) | docker login --password-stdin -u AWS $(AWS_ACCOUNT_ID).dkr.ecr.eu-west-1.amazonaws.com; \
hardcode region, you can use the ENV variable

2021-09-27 15:55 UTC, drAlberT commented on .github/workflows/deploy.yml
> +        aws --profile poser configure set region $AWS_REGION
I'm wondering why this is needed, as the SDK should be able to get the values from the ENV variables directly ..

2021-09-27 15:55 UTC, drAlberT commented on sys/cloudformation/stack.yaml
> +      UserName: github_action_deploy
```
  iamkey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref iamusergithubactions
```

should work

2022-01-10 18:51 UTC, merged