fix: stop check canary
PUGX/badge-poser pull request #681
Opened 2022-01-03 10:01 UTC by JellyBellyDev

I don't know why but from today I receive the following errors in dev environment that did 500.
I comment the lines in diff and now work!

@fabiocicerchia PTAL
 
```
badge-poser-nginx   | 172.18.0.1 - - [03/Jan/2022:09:43:47 +0000] "GET /phpunit/phpunit/composerlock HTTP/1.1" 500 572 "http://poser.local:8001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-" CACHE[GET@@poser.local@@/phpunit/phpunit/composerlock]:1:-
badge-poser-nginx   | 172.18.0.1 - - [03/Jan/2022:09:43:47 +0000] "GET /phpunit/phpunit/d/daily HTTP/1.1" 500 572 "http://poser.local:8001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-" CACHE[GET@@poser.local@@/phpunit/phpunit/d/daily]:1:-
badge-poser-nginx   | 172.18.0.1 - - [03/Jan/2022:09:43:47 +0000] "GET /phpunit/phpunit/version HTTP/1.1" 500 572 "http://poser.local:8001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-" CACHE[GET@@poser.local@@/phpunit/phpunit/version]:1:-
badge-poser-nginx   | 2022/01/03 09:43:47 [error] 29#29: *74 lua entry thread aborted: runtime error: /etc/nginx/conf.d/lua/hook.lua:26: attempt to compare number with nil
badge-poser-nginx   | stack traceback:
badge-poser-nginx   | coroutine 0:
badge-poser-nginx   | 	/etc/nginx/conf.d/lua/hook.lua: in main chunk, client: 172.18.0.1, server: poser.pugx.org, request: "GET /phpunit/phpunit/d/daily HTTP/1.1", host: "poser.local:8001", referrer: "http://poser.local:8001/"
badge-poser-nginx   | 2022/01/03 09:43:47 [error] 29#29: *73 lua entry thread aborted: runtime error: /etc/nginx/conf.d/lua/hook.lua:26: attempt to compare number with nil
badge-poser-nginx   | stack traceback:
badge-poser-nginx   | coroutine 0:
badge-poser-nginx   | 	/etc/nginx/conf.d/lua/hook.lua: in main chunk, client: 172.18.0.1, server: poser.pugx.org, request: "GET /phpunit/phpunit/version HTTP/1.1", host: "poser.local:8001", referrer: "http://poser.local:8001/"
badge-poser-nginx   | 172.18.0.1 - - [03/Jan/2022:09:43:47 +0000] "GET /phpunit/phpunit/dependents HTTP/1.1" 500 572 "http://poser.local:8001/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36" "-" CACHE[GET@@poser.local@@/phpunit/phpunit/dependents]:1:-
badge-poser-nginx   | 2022/01/03 09:43:47 [error] 29#29: *80 lua entry thread aborted: runtime error: /etc/nginx/conf.d/lua/hook.lua:26: attempt to compare number with nil
badge-poser-nginx   | stack traceback:
badge-poser-nginx   | coroutine 0:
badge-poser-nginx   | 	/etc/nginx/conf.d/lua/hook.lua: in main chunk, client: 172.18.0.1, server: poser.pugx.org, request: "GET /phpunit/phpunit/dependents HTTP/1.1", host: "poser.local:8001", referrer: "http://poser.local:8001/"
```

2022-01-10 18:57 UTC, fabiocicerchia requested changes
you could remove the entire block.
could you please remove the occurrences of `dark-canary` from `sys/nginx/default.conf.template` and `sys/cloudformation/stack.yaml`? :pray:

2022-01-10 18:57 UTC, fabiocicerchia commented on sys/nginx/lua/hook.lua
> +-- end
```suggestion
```

2022-01-10 18:57 UTC, fabiocicerchia commented on sys/nginx/lua/hook.lua
>  -- DARK CANARY
```suggestion
```

2022-01-11 08:56 UTC, JellyBellyDev commented
@fabiocicerchia PTAL

2022-01-24 11:18 UTC, merged