refactoring dev/prod env
PUGX/badge-poser pull request #732
Opened 2022-02-18 22:00 UTC by fabiocicerchia

2022-02-20 11:06 UTC, JellyBellyDev commented
@fabiocicerchia are you really asking me for the review or is it still in draft?

2022-03-01 13:01 UTC, fabiocicerchia commented
@JellyBellyDev yes, we can review this :)

2022-03-01 13:17 UTC, garak requested changes

2022-03-01 13:17 UTC, garak commented on composer.json
> +            "ocramius/package-versions": true
This is unsorted, it should be in the first place

2022-03-01 14:29 UTC, drAlberT commented on docker-compose.yml
> +      - ./.env.local
Are these used by nginx too?

2022-03-02 16:23 UTC, JellyBellyDev requested changes

2022-03-02 16:23 UTC, JellyBellyDev commented on docker-compose.yml
> +      - ./.env.local
`.env.test` to run tests in local?

2022-03-02 16:23 UTC, JellyBellyDev commented on sys/docker/alpine-phpfpm/Dockerfile.dev
> +FROM php:8.0.16-fpm-alpine
we can delete this file, no?

2022-03-02 16:31 UTC, JellyBellyDev commented
I tried to test `make start` and i have an error with:
`docker build -t awsbuilder -f sys/docker/common/Dockerfile.aws-ecs-ci .`
```
 => [2/3] RUN apt-get update &&      apt-get install -y ca-certificates curl &&     rm -rf /var/lib/apt/lists/*                                                                                                                                                            6.8s
 => ERROR [3/3] RUN curl -O https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb &&     dpkg -i -E amazon-cloudwatch-agent.deb &&     rm -rf /tmp/* &&     rm -rf /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agen  52.1s
------
 > [3/3] RUN curl -O https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb &&     dpkg -i -E amazon-cloudwatch-agent.deb &&     rm -rf /tmp/* &&     rm -rf /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard &&     rm -rf /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl &&     rm -rf /opt/aws/amazon-cloudwatch-agent/bin/config-downloader:
#6 0.137   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#6 0.137                                  Dload  Upload   Total   Spent    Left  Speed
100 57.5M  100 57.5M    0     0  1138k      0  0:00:51  0:00:51 --:--:-- 1884k
#6 51.99 dpkg: error processing archive amazon-cloudwatch-agent.deb (--install):
#6 51.99  package architecture (amd64) does not match system (arm64)
#6 52.01 Errors were encountered while processing:
#6 52.01  amazon-cloudwatch-agent.deb
------
executor failed running [/bin/sh -c curl -O https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb &&     dpkg -i -E amazon-cloudwatch-agent.deb &&     rm -rf /tmp/* &&     rm -rf /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard &&     rm -rf /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl &&     rm -rf /opt/aws/amazon-cloudwatch-agent/bin/config-downloader]: exit code: 1
make: *** [.docker_img_deps] Error 1
```

2022-03-02 17:03 UTC, fabiocicerchia commented
@JellyBellyDev the problem with `make start` should be fixed. It was due to arm64 arch, I guess you're on M1, right?

2022-03-02 18:24 UTC, JellyBellyDev commented
ok now the build works, but if I try to modify the sources I don't notice the modification on the web side.

2022-03-04 14:10 UTC, merged