Ricardoboss/master
PUGX/badge-poser pull request #733
Opened 2022-02-19 12:18 UTC by JellyBellyDev

2022-02-19 15:38 UTC, ricardoboss requested changes

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/AbstractBadgeController.php
> +    public function checkStyle(Request $request, Poser $poser, string $style = 'flat'): string
Maybe also use `Badge::DEFAULT_STYLE` here?

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/CircleCiController.php
> +        $style = 'flat',
Here `Badge::DEFAULT_FORMAT` and `Badge::DEFAULT_STYLE`?

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/ComposerLockController.php
> +        string $style = 'flat',
`Badge::DEFAULT_FORMAT` & `Badge::DEFAULT_STYLE`

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/DependentsController.php
> +        string $style = 'flat',
`Badge::DEFAULT_FORMAT` & `Badge::DEFAULT_STYLE`

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/DownloadsController.php
> +        string $style = 'flat',
`Badge::DEFAULT_FORMAT` & `Badge::DEFAULT_STYLE`

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/GitAttributesController.php
> +        string $style = 'flat',
`Badge::DEFAULT_FORMAT` & `Badge::DEFAULT_STYLE`

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/LicenseController.php
> +        string $style = 'flat',
`Badge::DEFAULT_FORMAT` & `Badge::DEFAULT_STYLE`

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/RequireController.php
> +        string $style = 'flat',
`Badge::DEFAULT_FORMAT` & `Badge::DEFAULT_STYLE`

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/SuggestersController.php
> +        string $style = 'flat',
`Badge::DEFAULT_FORMAT` & `Badge::DEFAULT_STYLE`

2022-02-19 15:38 UTC, ricardoboss commented on src/Controller/Badge/VersionController.php
> +        string $style = 'flat',
`Badge::DEFAULT_FORMAT` & `Badge::DEFAULT_STYLE`

2022-02-19 15:38 UTC, ricardoboss commented on tests/Badge/Model/UseCase/CreateDownloadsBadgeTest.php
> +        $badge = $this->useCase->createDownloadsBadge($repository, 'daily', 'svg', 'flat');
You could leave `'svg'` and `'flat'` out since they are determined by the parameter defaults.

2022-02-19 16:25 UTC, JellyBellyDev commented
@ricardoboss the PR it's you! change what you believe! ;)

2022-02-19 19:17 UTC, ricardoboss commented
No, you opened it...

2022-02-19 21:42 UTC, ricardoboss commented
@JellyBellyDev ok, but why did you open a new PR? What was wrong with the other one?

2022-02-19 22:15 UTC, ricardoboss approved these changes

2022-02-19 22:16 UTC, ricardoboss commented
@JellyBellyDev I updated badges/poser so `for-the-badge` should now be showing up for you.

2022-02-19 22:43 UTC, ricardoboss commented
@JellyBellyDev Don't know why the HomeControllerTest fails. Can reproduce it, but I'm not sure how to investigate. Can you help?

2022-02-20 10:54 UTC, JellyBellyDev commented
> @JellyBellyDev Don't know why the HomeControllerTest fails. Can reproduce it, but I'm not sure how to investigate. Can you help?

I fixed! ;)

2022-02-21 09:55 UTC, JellyBellyDev commented
@ricardoboss https://packagist.org/packages/badges/poser#v2.3.1 ;)

2022-02-21 10:21 UTC, JellyBellyDev commented
PTAL @garak @AlessandroMinoccheri @fabiocicerchia @antonkomarev

2022-02-21 11:21 UTC, ricardoboss commented
I think we should stick to already existing styles. This is a screenshot from https://shields.io/ and as you can see, the value is bold.

![image](https://user-images.githubusercontent.com/6266356/154945625-10a6b437-bd25-4dac-a4b0-be6a94c4640c.png)

2022-02-21 11:37 UTC, JellyBellyDev commented
@ricardoboss can you squash the commits please?

2022-02-21 11:39 UTC, ricardoboss commented
You mean this?

![image](https://user-images.githubusercontent.com/6266356/154948201-043ce238-1bd3-4594-8f0a-a23b4148a8e2.png)

2022-02-21 11:43 UTC, JellyBellyDev commented
> You mean this?
> 
> ![image](https://user-images.githubusercontent.com/6266356/154948201-043ce238-1bd3-4594-8f0a-a23b4148a8e2.png)

no, i mean rebase this branch with one single commit chosen by you and `push -f`.  
please leave the merge action to me! ;)

2022-02-21 21:58 UTC, AlessandroMinoccheri approved these changes
Many changes, but it seems good to me.

2022-02-22 08:24 UTC, merged